#define EGG_GROUP_NONE "None"
#define EGG_GROUP_MONSTER "Monster"
#define EGG_GROUP_WATER_1 "Water 1"
#define EGG_GROUP_BUG "Bug"
#define EGG_GROUP_FLYING "Flying"
#define EGG_GROUP_FIELD "Field"
#define EGG_GROUP_FAIRY "Fairy"
#define EGG_GROUP_GRASS "Grass"
#define EGG_GROUP_HUMAN_LIKE "Human Like"
#define EGG_GROUP_WATER_3 "Water 3"
#define EGG_GROUP_MINERAL "Mineral"
#define EGG_GROUP_AMORPHOUS "Amorphous"
#define EGG_GROUP_WATER_2 "Water 2"
#define EGG_GROUP_DITTO "Ditto"
#define EGG_GROUP_DRAGON "Dragon "
#define EGG_GROUP_UNDISCOVERED "Undiscovered"