#define UNBOUND true

#define ITEM_NONE "NONE"
#define ITEM_MASTER_BALL "MASTER_BALL"
#define ITEM_ULTRA_BALL "ULTRA_BALL"
#define ITEM_GREAT_BALL "GREAT_BALL"
#define ITEM_POKE_BALL "POKE_BALL"
#define ITEM_SAFARI_BALL "SAFARI_BALL"
#define ITEM_NET_BALL "NET_BALL"
#define ITEM_DIVE_BALL "DIVE_BALL"
#define ITEM_NEST_BALL "NEST_BALL"
#define ITEM_REPEAT_BALL "REPEAT_BALL"
#define ITEM_TIMER_BALL "TIMER_BALL"
#define ITEM_LUXURY_BALL "LUXURY_BALL"
#define ITEM_PREMIER_BALL "PREMIER_BALL"
#define ITEM_POTION "POTION"
#define ITEM_ANTIDOTE "ANTIDOTE"
#define ITEM_BURN_HEAL "BURN_HEAL"
#define ITEM_ICE_HEAL "ICE_HEAL"
#define ITEM_AWAKENING "AWAKENING"
#define ITEM_PARALYZE_HEAL "PARALYZE_HEAL"
#define ITEM_FULL_RESTORE "FULL_RESTORE"
#define ITEM_MAX_POTION "MAX_POTION"
#define ITEM_HYPER_POTION "HYPER_POTION"
#define ITEM_SUPER_POTION "SUPER_POTION"
#define ITEM_FULL_HEAL "FULL_HEAL"
#define ITEM_REVIVE "REVIVE"
#define ITEM_MAX_REVIVE "MAX_REVIVE"
#define ITEM_FRESH_WATER "FRESH_WATER"
#define ITEM_SODA_POP "SODA_POP"
#define ITEM_LEMONADE "LEMONADE"
#define ITEM_MOOMOO_MILK "MOOMOO_MILK"
#define ITEM_ENERGY_POWDER "ENERGY_POWDER"
#define ITEM_ENERGY_ROOT "ENERGY_ROOT"
#define ITEM_HEAL_POWDER "HEAL_POWDER"
#define ITEM_REVIVAL_HERB "REVIVAL_HERB"
#define ITEM_ETHER "ETHER"
#define ITEM_MAX_ETHER "MAX_ETHER"
#define ITEM_ELIXIR "ELIXIR"
#define ITEM_MAX_ELIXIR "MAX_ELIXIR"
#define ITEM_LAVA_COOKIE "LAVA_COOKIE"
#define ITEM_BLUE_FLUTE "BLUE_FLUTE"
#define ITEM_YELLOW_FLUTE "YELLOW_FLUTE"
#define ITEM_RED_FLUTE "RED_FLUTE"
#define ITEM_BLACK_FLUTE "BLACK_FLUTE"
#define ITEM_WHITE_FLUTE "WHITE_FLUTE"
#define ITEM_BERRY_JUICE "BERRY_JUICE"
#define ITEM_SACRED_ASH "SACRED_ASH"
#define ITEM_SHOAL_SALT "SHOAL_SALT"
#define ITEM_SHOAL_SHELL "SHOAL_SHELL"
#define ITEM_RED_SHARD "RED_SHARD"
#define ITEM_BLUE_SHARD "BLUE_SHARD"
#define ITEM_YELLOW_SHARD "YELLOW_SHARD"
#define ITEM_GREEN_SHARD "GREEN_SHARD"
#define ITEM_034 "034"
#define ITEM_035 "035"
#define ITEM_036 "036"
#define ITEM_037 "037"
#define ITEM_038 "038"
#define ITEM_039 "039"
#define ITEM_03A "03A"
#define ITEM_03B "03B"
#define ITEM_03C "03C"
#define ITEM_03D "03D"
#define ITEM_03E "03E"
#define ITEM_HP_UP "HP_UP"
#define ITEM_PROTEIN "PROTEIN"
#define ITEM_IRON "IRON"
#define ITEM_CARBOS "CARBOS"
#define ITEM_CALCIUM "CALCIUM"
#define ITEM_RARE_CANDY "RARE_CANDY"
#define ITEM_PP_UP "PP_UP"
#define ITEM_ZINC "ZINC"
#define ITEM_PP_MAX "PP_MAX"
#define ITEM_048 "048"
#define ITEM_GUARD_SPEC "GUARD_SPEC"
#define ITEM_DIRE_HIT "DIRE_HIT"
#define ITEM_X_ATTACK "X_ATTACK"
#define ITEM_X_DEFEND "X_DEFEND"
#define ITEM_X_SPEED "X_SPEED"
#define ITEM_X_ACCURACY "X_ACCURACY"
#define ITEM_X_SP_ATK "X_SP_ATK"
#define ITEM_POKE_DOLL "POKE_DOLL"
#define ITEM_FLUFFY_TAIL "FLUFFY_TAIL"
#define ITEM_X_SP_DEF "X_SP_DEF"
#define ITEM_SUPER_REPEL "SUPER_REPEL"
#define ITEM_MAX_REPEL "MAX_REPEL"
#define ITEM_ESCAPE_ROPE "ESCAPE_ROPE"
#define ITEM_REPEL "REPEL"
#define ITEM_057 "057"
#define ITEM_058 "058"
#define ITEM_059 "059"
#define ITEM_05A "05A"
#define ITEM_05B "05B"
#define ITEM_05C "05C"
#define ITEM_SUN_STONE "SUN_STONE"
#define ITEM_MOON_STONE "MOON_STONE"
#define ITEM_FIRE_STONE "FIRE_STONE"
#define ITEM_THUNDER_STONE "THUNDER_STONE"
#define ITEM_WATER_STONE "WATER_STONE"
#define ITEM_LEAF_STONE "LEAF_STONE"
#define ITEM_063 "063"
#define ITEM_064 "064"
#define ITEM_065 "065"
#define ITEM_066 "066"
#define ITEM_TINY_MUSHROOM "TINY_MUSHROOM"
#define ITEM_BIG_MUSHROOM "BIG_MUSHROOM"
#define ITEM_069 "069"
#define ITEM_PEARL "PEARL"
#define ITEM_BIG_PEARL "BIG_PEARL"
#define ITEM_STARDUST "STARDUST"
#define ITEM_STAR_PIECE "STAR_PIECE"
#define ITEM_NUGGET "NUGGET"
#define ITEM_HEART_SCALE "HEART_SCALE"
#define ITEM_070 "070"
#define ITEM_071 "071"
#define ITEM_072 "072"
#define ITEM_073 "073"
#define ITEM_074 "074"
#define ITEM_075 "075"
#define ITEM_076 "076"
#define ITEM_077 "077"
#define ITEM_078 "078"
#define ITEM_ORANGE_MAIL "ORANGE_MAIL"
#define ITEM_HARBOR_MAIL "HARBOR_MAIL"
#define ITEM_GLITTER_MAIL "GLITTER_MAIL"
#define ITEM_MECH_MAIL "MECH_MAIL"
#define ITEM_WOOD_MAIL "WOOD_MAIL"
#define ITEM_WAVE_MAIL "WAVE_MAIL"
#define ITEM_BEAD_MAIL "BEAD_MAIL"
#define ITEM_SHADOW_MAIL "SHADOW_MAIL"
#define ITEM_TROPIC_MAIL "TROPIC_MAIL"
#define ITEM_DREAM_MAIL "DREAM_MAIL"
#define ITEM_FAB_MAIL "FAB_MAIL"
#define ITEM_RETRO_MAIL "RETRO_MAIL"
#define ITEM_CHERI_BERRY "CHERI_BERRY"
#define ITEM_CHESTO_BERRY "CHESTO_BERRY"
#define ITEM_PECHA_BERRY "PECHA_BERRY"
#define ITEM_RAWST_BERRY "RAWST_BERRY"
#define ITEM_ASPEAR_BERRY "ASPEAR_BERRY"
#define ITEM_LEPPA_BERRY "LEPPA_BERRY"
#define ITEM_ORAN_BERRY "ORAN_BERRY"
#define ITEM_PERSIM_BERRY "PERSIM_BERRY"
#define ITEM_LUM_BERRY "LUM_BERRY"
#define ITEM_SITRUS_BERRY "SITRUS_BERRY"
#define ITEM_FIGY_BERRY "FIGY_BERRY"
#define ITEM_WIKI_BERRY "WIKI_BERRY"
#define ITEM_MAGO_BERRY "MAGO_BERRY"
#define ITEM_AGUAV_BERRY "AGUAV_BERRY"
#define ITEM_IAPAPA_BERRY "IAPAPA_BERRY"
#define ITEM_RAZZ_BERRY "RAZZ_BERRY"
#define ITEM_BLUK_BERRY "BLUK_BERRY"
#define ITEM_NANAB_BERRY "NANAB_BERRY"
#define ITEM_WEPEAR_BERRY "WEPEAR_BERRY"
#define ITEM_PINAP_BERRY "PINAP_BERRY"
#define ITEM_POMEG_BERRY "POMEG_BERRY"
#define ITEM_KELPSY_BERRY "KELPSY_BERRY"
#define ITEM_QUALOT_BERRY "QUALOT_BERRY"
#define ITEM_HONDEW_BERRY "HONDEW_BERRY"
#define ITEM_GREPA_BERRY "GREPA_BERRY"
#define ITEM_TAMATO_BERRY "TAMATO_BERRY"
#define ITEM_CORNN_BERRY "CORNN_BERRY"
#define ITEM_MAGOST_BERRY "MAGOST_BERRY"
#define ITEM_RABUTA_BERRY "RABUTA_BERRY"
#define ITEM_NOMEL_BERRY "NOMEL_BERRY"
#define ITEM_SPELON_BERRY "SPELON_BERRY"
#define ITEM_PAMTRE_BERRY "PAMTRE_BERRY"
#define ITEM_WATMEL_BERRY "WATMEL_BERRY"
#define ITEM_DURIN_BERRY "DURIN_BERRY"
#define ITEM_BELUE_BERRY "BELUE_BERRY"
#define ITEM_LIECHI_BERRY "LIECHI_BERRY"
#define ITEM_GANLON_BERRY "GANLON_BERRY"
#define ITEM_SALAC_BERRY "SALAC_BERRY"
#define ITEM_PETAYA_BERRY "PETAYA_BERRY"
#define ITEM_APICOT_BERRY "APICOT_BERRY"
#define ITEM_LANSAT_BERRY "LANSAT_BERRY"
#define ITEM_STARF_BERRY "STARF_BERRY"
#define ITEM_ENIGMA_BERRY_OLD "ENIGMA_BERRY_OLD"
#define ITEM_ENIGMA_BERRY "ENIGMA_BERRY"
#define ITEM_0B0 "0B0"
#define ITEM_0B1 "0B1"
#define ITEM_0B2 "0B2"
#define ITEM_BRIGHT_POWDER "BRIGHT_POWDER"
#define ITEM_WHITE_HERB "WHITE_HERB"
#define ITEM_MACHO_BRACE "MACHO_BRACE"
#define ITEM_EXP_SHARE "EXP_SHARE"
#define ITEM_QUICK_CLAW "QUICK_CLAW"
#define ITEM_SOOTHE_BELL "SOOTHE_BELL"
#define ITEM_MENTAL_HERB "MENTAL_HERB"

#ifdef UNBOUND
#define ITEM_CHOICE_BAND "CHOICE_BAND"
#else
#define ITEM_CHOICE_BAND "CHOICE_BAND"
#endif

#define ITEM_KINGS_ROCK "KINGS_ROCK"
#define ITEM_SILVER_POWDER "SILVER_POWDER"
#define ITEM_AMULET_COIN "AMULET_COIN"
#define ITEM_CLEANSE_TAG "CLEANSE_TAG"
#define ITEM_SOUL_DEW "SOUL_DEW"
#define ITEM_DEEP_SEA_TOOTH "DEEP_SEA_TOOTH"
#define ITEM_DEEP_SEA_SCALE "DEEP_SEA_SCALE"
#define ITEM_SMOKE_BALL "SMOKE_BALL"
#define ITEM_EVERSTONE "EVERSTONE"
#define ITEM_FOCUS_BAND "FOCUS_BAND"
#define ITEM_LUCKY_EGG "LUCKY_EGG"
#define ITEM_SCOPE_LENS "SCOPE_LENS"
#define ITEM_METAL_COAT "METAL_COAT"
#define ITEM_LEFTOVERS "LEFTOVERS"
#define ITEM_DRAGON_SCALE "DRAGON_SCALE"
#define ITEM_LIGHT_BALL "LIGHT_BALL"
#define ITEM_SOFT_SAND "SOFT_SAND"
#define ITEM_HARD_STONE "HARD_STONE"
#define ITEM_MIRACLE_SEED "MIRACLE_SEED"
#define ITEM_BLACK_GLASSES "BLACK_GLASSES"
#define ITEM_BLACK_BELT "BLACK_BELT"
#define ITEM_MAGNET "MAGNET"
#define ITEM_MYSTIC_WATER "MYSTIC_WATER"
#define ITEM_SHARP_BEAK "SHARP_BEAK"
#define ITEM_POISON_BARB "POISON_BARB"
#define ITEM_NEVER_MELT_ICE "NEVER_MELT_ICE"
#define ITEM_SPELL_TAG "SPELL_TAG"
#define ITEM_TWISTED_SPOON "TWISTED_SPOON"
#define ITEM_CHARCOAL "CHARCOAL"
#define ITEM_DRAGON_FANG "DRAGON_FANG"
#define ITEM_SILK_SCARF "SILK_SCARF"
#define ITEM_UP_GRADE "UP_GRADE"
#define ITEM_SHELL_BELL "SHELL_BELL"
#define ITEM_SEA_INCENSE "SEA_INCENSE"
#define ITEM_LAX_INCENSE "LAX_INCENSE"
#define ITEM_LUCKY_PUNCH "LUCKY_PUNCH"
#define ITEM_METAL_POWDER "METAL_POWDER"
#define ITEM_THICK_CLUB "THICK_CLUB"
#define ITEM_LEEK "LEEK"
#define ITEM_0E2 "0E2"
#define ITEM_0E3 "0E3"
#define ITEM_0E4 "0E4"
#define ITEM_0E5 "0E5"
#define ITEM_0E6 "0E6"
#define ITEM_0E7 "0E7"
#define ITEM_0E8 "0E8"
#define ITEM_0E9 "0E9"
#define ITEM_0EA "0EA"
#define ITEM_0EB "0EB"
#define ITEM_0EC "0EC"
#define ITEM_0ED "0ED"
#define ITEM_0EE "0EE"
#define ITEM_0EF "0EF"
#define ITEM_0F0 "0F0"
#define ITEM_0F1 "0F1"
#define ITEM_0F2 "0F2"
#define ITEM_0F3 "0F3"
#define ITEM_0F4 "0F4"
#define ITEM_0F5 "0F5"
#define ITEM_0F6 "0F6"
#define ITEM_0F7 "0F7"
#define ITEM_0F8 "0F8"
#define ITEM_0F9 "0F9"
#define ITEM_0FA "0FA"
#define ITEM_0FB "0FB"
#define ITEM_0FC "0FC"
#define ITEM_0FD "0FD"
#define ITEM_RED_SCARF "RED_SCARF"
#define ITEM_BLUE_SCARF "BLUE_SCARF"
#define ITEM_PINK_SCARF "PINK_SCARF"
#define ITEM_GREEN_SCARF "GREEN_SCARF"
#define ITEM_YELLOW_SCARF "YELLOW_SCARF"
#define ITEM_MACH_BIKE "MACH_BIKE"
#define ITEM_COIN_CASE "COIN_CASE"
#define ITEM_ITEMFINDER "ITEMFINDER"
#define ITEM_OLD_ROD "OLD_ROD"
#define ITEM_GOOD_ROD "GOOD_ROD"
#define ITEM_SUPER_ROD "SUPER_ROD"
#define ITEM_SS_TICKET "SS_TICKET"
#define ITEM_CONTEST_PASS "CONTEST_PASS"
#define ITEM_10B "10B"
#define ITEM_WAILMER_PAIL "WAILMER_PAIL"
#define ITEM_DEVON_GOODS "DEVON_GOODS"
#define ITEM_SOOT_SACK "SOOT_SACK"
#define ITEM_BASEMENT_KEY "BASEMENT_KEY"
#define ITEM_ACRO_BIKE "ACRO_BIKE"
#define ITEM_POKEBLOCK_CASE "POKEBLOCK_CASE"
#define ITEM_LETTER "LETTER"
#define ITEM_EON_TICKET "EON_TICKET"
#define ITEM_RED_ORB "RED_ORB"
#define ITEM_BLUE_ORB "BLUE_ORB"
#define ITEM_SCANNER "SCANNER"
#define ITEM_GO_GOGGLES "GO_GOGGLES"
#define ITEM_METEORITE "METEORITE"
#define ITEM_ROOM_1_KEY "ROOM_1_KEY"
#define ITEM_ROOM_2_KEY "ROOM_2_KEY"
#define ITEM_ROOM_4_KEY "ROOM_4_KEY"
#define ITEM_ROOM_6_KEY "ROOM_6_KEY"
#define ITEM_STORAGE_KEY "STORAGE_KEY"
#define ITEM_ROOT_FOSSIL "ROOT_FOSSIL"
#define ITEM_CLAW_FOSSIL "CLAW_FOSSIL"
#define ITEM_DEVON_SCOPE "DEVON_SCOPE"

#ifndef UNBOUND // Modify this
enum
{
    ITEM_TM01_FOCUS_PUNCH = 0x121,
    ITEM_TM02_DRAGON_CLAW,
    ITEM_TM03_WATER_PULSE,
    ITEM_TM04_CALM_MIND,
    ITEM_TM05_ROAR,
    ITEM_TM06_TOXIC,
    ITEM_TM07_HAIL,
    ITEM_TM08_BULK_UP,
    ITEM_TM09_BULLET_SEED,
    ITEM_TM10_HIDDEN_POWER,
    ITEM_TM11_SUNNY_DAY,
    ITEM_TM12_TAUNT,
    ITEM_TM13_ICE_BEAM,
    ITEM_TM14_BLIZZARD,
    ITEM_TM15_HYPER_BEAM,
    ITEM_TM16_LIGHT_SCREEN,
    ITEM_TM17_PROTECT,
    ITEM_TM18_RAIN_DANCE,
    ITEM_TM19_GIGA_DRAIN,
    ITEM_TM20_SAFEGUARD,
    ITEM_TM21_FRUSTRATION,
    ITEM_TM22_SOLARBEAM,
    ITEM_TM23_IRON_TAIL,
    ITEM_TM24_THUNDERBOLT,
    ITEM_TM25_THUNDER,
    ITEM_TM26_EARTHQUAKE,
    ITEM_TM27_RETURN,
    ITEM_TM28_DIG,
    ITEM_TM29_PSYCHIC,
    ITEM_TM30_SHADOW_BALL,
    ITEM_TM31_BRICK_BREAK,
    ITEM_TM32_DOUBLE_TEAM,
    ITEM_TM33_REFLECT,
    ITEM_TM34_SHOCK_WAVE,
    ITEM_TM35_FLAMETHROWER,
    ITEM_TM36_SLUDGE_BOMB,
    ITEM_TM37_SANDSTORM,
    ITEM_TM38_FIRE_BLAST,
    ITEM_TM39_ROCK_TOMB,
    ITEM_TM40_AERIAL_ACE,
    ITEM_TM41_TORMENT,
    ITEM_TM42_FACADE,
    ITEM_TM43_SECRET_POWER,
    ITEM_TM44_REST,
    ITEM_TM45_ATTRACT,
    ITEM_TM46_THIEF,
    ITEM_TM47_STEEL_WING,
    ITEM_TM48_SKILL_SWAP,
    ITEM_TM49_LEECH_FANG,
    ITEM_TM50_OVERHEAT,
    ITEM_HM01_CUT,
    ITEM_HM02_FLY,
    ITEM_HM03_SURF,
    ITEM_HM04_STRENGTH,
    ITEM_HM05_DIVE,
    ITEM_HM06_ROCK_SMASH,
    ITEM_HM07_WATERFALL,
    ITEM_HM08_ROCK_CLIMB,
};

// New TMs
#define ITEM_TM51 "TM51"
#define ITEM_TM52 "TM52"
#define ITEM_TM53 "TM53"
#define ITEM_TM54 "TM54"
#define ITEM_TM55 "TM55"
#define ITEM_TM56 "TM56"
#define ITEM_TM57 "TM57"
#define ITEM_TM58 "TM58"
enum
{
    ITEM_TM59_DRAGON_PULSE = 0x177,
    ITEM_TM60_DRAIN_PUNCH,
    ITEM_TM61_WILL_O_WISP,
    ITEM_TM62_SILVER_WIND,
    ITEM_TM63_VENOSHOCK,
    ITEM_TM64_EXPLOSION,
    ITEM_TM65_SHADOW_CLAW,
    ITEM_TM66_PAYBACK,
    ITEM_TM67_RECYCLE,
    ITEM_TM68_GIGA_IMPACT,
    ITEM_TM69_ROCK_POLISH,
    ITEM_TM70_FLASH,
    ITEM_TM71_STONE_EDGE,
    ITEM_TM72_AVALANCHE,
    ITEM_TM73_THUNDER_WAVE,
    ITEM_TM74_GYRO_BALL,
    ITEM_TM75_SWORDS_DANCE,
    ITEM_TM76_STEALTH_ROCK,
    ITEM_TM77_FLAME_CHARGE,
    ITEM_TM78_LOW_SWEEP,
    ITEM_TM79_DARK_PULSE,
    ITEM_TM80_ROCK_SLIDE,
    ITEM_TM81_X_SCISSOR,
    ITEM_TM82_SLEEP_TALK,
    ITEM_TM83_SCALD,
    ITEM_TM84_POISON_JAB,
    ITEM_TM85_DREAM_EATER,
    ITEM_TM86_GRASS_KNOT,
    ITEM_TM87_SWAGGER,
    ITEM_TM88_PLUCK,
    ITEM_TM89_U_TURN,
    ITEM_TM90_SUBSTITUTE,
    ITEM_TM91_FLASH_CANNON,
    ITEM_TM92_VOLT_SWITCH,
    ITEM_TM93_DRAGON_TAIL,
    ITEM_TM94_INCINERATE,
    ITEM_TM95_STRUGGLE_BUG,
    ITEM_TM96_BULLDOZE,
    ITEM_TM97_FROST_BREATH,
    ITEM_TM98_WORK_UP,
    ITEM_TM99_WILD_CHARGE,
    ITEM_TM100_INFESTATION,
    ITEM_TM101_POWER_UP_PUNCH,
    ITEM_TM102_DAZZLING_GLEAM,
    ITEM_TM103_SLUDGE_WAVE,
    ITEM_TM104_PSYSHOCK,
    ITEM_TM105_BRUTAL_SWING,
    ITEM_TM106_SMART_STRIKE,
    ITEM_TM107_ACROBATICS,
    ITEM_TM108_SNARL,
    ITEM_TM109_DEFOG,
    ITEM_TM110_DRAINING_KISS,
    ITEM_TM111_SMACK_DOWN,
    ITEM_TM112_ROUND,
    ITEM_TM113_ECHOED_VOICE,
    ITEM_TM114_NATURAL_GIFT,
    ITEM_TM115_QUASH,
    ITEM_TM116_TRICK_ROOM,
    ITEM_TM117_FLING,
    ITEM_TM118_AURORA_VEIL,
    ITEM_TM119_SKY_DROP,
    ITEM_TM120_NATURE_POWER,
};
#endif

#define ITEM_15B "15B"
#define ITEM_15C "15C"

// FireRed/LeafGreen
#define ITEM_OAKS_PARCEL "OAKS_PARCEL"
#define ITEM_POKE_FLUTE "POKE_FLUTE"
#define ITEM_SECRET_KEY "SECRET_KEY"
#define ITEM_BIKE_VOUCHER "BIKE_VOUCHER"
#define ITEM_GOLD_TEETH "GOLD_TEETH"
#define ITEM_OLD_AMBER "OLD_AMBER"
#define ITEM_CARD_KEY "CARD_KEY"
#define ITEM_LIFT_KEY "LIFT_KEY"
#define ITEM_HELIX_FOSSIL "HELIX_FOSSIL"
#define ITEM_DOME_FOSSIL "DOME_FOSSIL"
#define ITEM_SILPH_SCOPE "SILPH_SCOPE"
#define ITEM_BICYCLE "BICYCLE"
#define ITEM_TOWN_MAP "TOWN_MAP"
#define ITEM_VS_SEEKER "VS_SEEKER"
#define ITEM_FAME_CHECKER "FAME_CHECKER"
#define ITEM_TM_CASE "TM_CASE"
#define ITEM_BERRY_POUCH "BERRY_POUCH"
#define ITEM_TEACHY_TV "TEACHY_TV"
#define ITEM_TRI_PASS "TRI_PASS"
#define ITEM_RAINBOW_PASS "RAINBOW_PASS"
#define ITEM_TEA "TEA"
#define ITEM_MYSTIC_TICKET "MYSTIC_TICKET"
#define ITEM_AURORA_TICKET "AURORA_TICKET"
#define ITEM_POWDER_JAR "POWDER_JAR"
#define ITEM_RUBY "RUBY"
#define ITEM_SAPPHIRE "SAPPHIRE"
#define ITEM_N_A "N_A"

// New Sellable Items
#define ITEM_RARE_BONE "RARE_BONE"
#define ITEM_PEARL_STRING "PEARL_STRING"
#define ITEM_BIG_NUGGET "BIG_NUGGET"
#define ITEM_COMET_SHARD "COMET_SHARD"
#define ITEM_BALM_MUSHROOM "BALM_MUSHROOM"

// New Food Items
#define ITEM_HONEY "HONEY"
#define ITEM_BIG_MALASADA "BIG_MALASADA"
#define ITEM_CASTELIACONE "CASTELIACONE"
#define ITEM_LUMIOSE_GALETTE "LUMIOSE_GALETTE"
#define ITEM_RAGE_CANDY_BAR "RAGE_CANDY_BAR"
#define ITEM_SHALOUR_SABLE "SHALOUR_SABLE"
#define ITEM_OLD_GATEAU "OLD_GATEAU"

// Fossils
#define ITEM_SKULL_FOSSIL "SKULL_FOSSIL"
#define ITEM_ARMOR_FOSSIL "ARMOR_FOSSIL"
#define ITEM_COVER_FOSSIL "COVER_FOSSIL"
#define ITEM_PLUME_FOSSIL "PLUME_FOSSIL"
#define ITEM_JAW_FOSSIL "JAW_FOSSIL"
#define ITEM_SAIL_FOSSIL "SAIL_FOSSIL"

// EV Gain Items
#define ITEM_POWER_BRACER "POWER_BRACER"
#define ITEM_POWER_BELT "POWER_BELT"
#define ITEM_POWER_LENS "POWER_LENS"
#define ITEM_POWER_BAND "POWER_BAND"
#define ITEM_POWER_ANKLET "POWER_ANKLET"
#define ITEM_POWER_WEIGHT "POWER_WEIGHT"

// New Battle Hold Items
#define ITEM_ADAMANT_ORB "ADAMANT_ORB"
#define ITEM_LUSTROUS_ORB "LUSTROUS_ORB"
#define ITEM_GRISEOUS_ORB "GRISEOUS_ORB"

#define ITEM_EXPERT_BELT "EXPERT_BELT"
#define ITEM_POWER_HERB "POWER_HERB"
#define ITEM_WIDE_LENS "WIDE_LENS"
#define ITEM_ZOOM_LENS "ZOOM_LENS"
#define ITEM_DESTINY_KNOT "DESTINY_KNOT"
#define ITEM_SMOOTH_ROCK "SMOOTH_ROCK"
#define ITEM_DAMP_ROCK "DAMP_ROCK"
#define ITEM_HEAT_ROCK "HEAT_ROCK"
#define ITEM_ICY_ROCK "ICY_ROCK"
#define ITEM_BIG_ROOT "BIG_ROOT"
#define ITEM_LIGHT_CLAY "LIGHT_CLAY"
#define ITEM_SAFETY_GOGGLES "SAFETY_GOGGLES"
#define ITEM_ROCKY_HELMET "ROCKY_HELMET"
#define ITEM_WEAKNESS_POLICY "WEAKNESS_POLICY"
#define ITEM_ASSAULT_VEST "ASSAULT_VEST"
#define ITEM_EVIOLITE "EVIOLITE"
#define ITEM_ABSORB_BULB "ABSORB_BULB"
#define ITEM_AIR_BALLOON "AIR_BALLOON"
#define ITEM_ADRENALINE_ORB "ADRENALINE_ORB"
#define ITEM_BINDING_BAND "BINDING_BAND"
#define ITEM_CELL_BATTERY "CELL_BATTERY"
#define ITEM_EJECT_BUTTON "EJECT_BUTTON"
#define ITEM_FLOAT_STONE "FLOAT_STONE"
#define ITEM_FOCUS_SASH "FOCUS_SASH"
#define ITEM_GRIP_CLAW "GRIP_CLAW"
#define ITEM_IRON_BALL "IRON_BALL"
#define ITEM_LAGGING_TAIL "LAGGING_TAIL"
#define ITEM_LUMINOUS_MOSS "LUMINOUS_MOSS"
#define ITEM_QUICK_POWDER "QUICK_POWDER"
#define ITEM_METRONOME "METRONOME"
#define ITEM_MUSCLE_BAND "MUSCLE_BAND"
#define ITEM_PROTECTIVE_PADS "PROTECTIVE_PADS"
#define ITEM_RED_CARD "RED_CARD"
#define ITEM_RING_TARGET "RING_TARGET"
#define ITEM_SHED_SHELL "SHED_SHELL"
#define ITEM_SNOWBALL "SNOWBALL"
#define ITEM_STICKY_BARB "STICKY_BARB"
#define ITEM_TERRAIN_EXTENDER "TERRAIN_EXTENDER"
#define ITEM_WISE_GLASSES "WISE_GLASSES"
#define ITEM_ELECTRIC_SEED "ELECTRIC_SEED"
#define ITEM_GRASSY_SEED "GRASSY_SEED"
#define ITEM_MISTY_SEED "MISTY_SEED"
#define ITEM_PSYCHIC_SEED "PSYCHIC_SEED"

#define ITEM_LIFE_ORB "LIFE_ORB"
#define ITEM_TOXIC_ORB "TOXIC_ORB"
#define ITEM_FLAME_ORB "FLAME_ORB"
#define ITEM_BLACK_SLUDGE "BLACK_SLUDGE"

#define ITEM_CHOICE_SPECS "CHOICE_SPECS"
#define ITEM_CHOICE_SCARF "CHOICE_SCARF"

// New Incense
#define ITEM_LUCK_INCENSE "LUCK_INCENSE"
#define ITEM_FULL_INCENSE "FULL_INCENSE"
#define ITEM_ODD_INCENSE "ODD_INCENSE"
#define ITEM_PURE_INCENSE "PURE_INCENSE"
#define ITEM_ROCK_INCENSE "ROCK_INCENSE"
#define ITEM_ROSE_INCENSE "ROSE_INCENSE"
#define ITEM_WAVE_INCENSE "WAVE_INCENSE"

// Gems
#define ITEM_NORMAL_GEM "NORMAL_GEM"
#define ITEM_FIGHTING_GEM "FIGHTING_GEM"
#define ITEM_FLYING_GEM "FLYING_GEM"
#define ITEM_POISON_GEM "POISON_GEM"
#define ITEM_GROUND_GEM "GROUND_GEM"
#define ITEM_ROCK_GEM "ROCK_GEM"
#define ITEM_BUG_GEM "BUG_GEM"
#define ITEM_GHOST_GEM "GHOST_GEM"
#define ITEM_STEEL_GEM "STEEL_GEM"
#define ITEM_FIRE_GEM "FIRE_GEM"
#define ITEM_WATER_GEM "WATER_GEM"
#define ITEM_GRASS_GEM "GRASS_GEM"
#define ITEM_ELECTRIC_GEM "ELECTRIC_GEM"
#define ITEM_PSYCHIC_GEM "PSYCHIC_GEM"
#define ITEM_ICE_GEM "ICE_GEM"
#define ITEM_DRAGON_GEM "DRAGON_GEM"
#define ITEM_DARK_GEM "DARK_GEM"
#define ITEM_FAIRY_GEM "FAIRY_GEM"

// Arceus Plates
#define ITEM_FIST_PLATE "FIST_PLATE"
#define ITEM_SKY_PLATE "SKY_PLATE"
#define ITEM_TOXIC_PLATE "TOXIC_PLATE"
#define ITEM_EARTH_PLATE "EARTH_PLATE"
#define ITEM_STONE_PLATE "STONE_PLATE"
#define ITEM_INSECT_PLATE "INSECT_PLATE"
#define ITEM_SPOOKY_PLATE "SPOOKY_PLATE"
#define ITEM_IRON_PLATE "IRON_PLATE"
#define ITEM_FLAME_PLATE "FLAME_PLATE"
#define ITEM_SPLASH_PLATE "SPLASH_PLATE"
#define ITEM_MEADOW_PLATE "MEADOW_PLATE"
#define ITEM_ZAP_PLATE "ZAP_PLATE"
#define ITEM_MIND_PLATE "MIND_PLATE"
#define ITEM_ICICLE_PLATE "ICICLE_PLATE"
#define ITEM_DRACO_PLATE "DRACO_PLATE"
#define ITEM_DREAD_PLATE "DREAD_PLATE"
#define ITEM_PIXIE_PLATE "PIXIE_PLATE"

// Mega Stones
#define ITEM_MEGA_RING "MEGA_RING"

#define ITEM_ULTRANECROZIUM_Z "ULTRANECROZIUM_Z"
#define ITEM_VENUSAURITE "VENUSAURITE"
#define ITEM_CHARIZARDITE_X "CHARIZARDITE_X"
#define ITEM_CHARIZARDITE_Y "CHARIZARDITE_Y"
#define ITEM_BLASTOISINITE "BLASTOISINITE"
#define ITEM_BEEDRILLITE "BEEDRILLITE"
#define ITEM_PIDGEOTITE "PIDGEOTITE"
#define ITEM_ALAKAZITE "ALAKAZITE"
#define ITEM_SLOWBRONITE "SLOWBRONITE"
#define ITEM_GENGARITE "GENGARITE"
#define ITEM_KANGASKHANITE "KANGASKHANITE"
#define ITEM_PINSIRITE "PINSIRITE"
#define ITEM_GYARADOSITE "GYARADOSITE"
#define ITEM_AERODACTYLITE "AERODACTYLITE"
#define ITEM_MEWTWONITE_X "MEWTWONITE_X"
#define ITEM_MEWTWONITE_Y "MEWTWONITE_Y"
#define ITEM_AMPHAROSITE "AMPHAROSITE"
#define ITEM_STEELIXITE "STEELIXITE"
#define ITEM_SCIZORITE "SCIZORITE"
#define ITEM_HERACRONITE "HERACRONITE"
#define ITEM_HOUNDOOMINITE "HOUNDOOMINITE"
#define ITEM_TYRANITARITE "TYRANITARITE"
#define ITEM_SCEPTILITE "SCEPTILITE"
#define ITEM_BLAZIKENITE "BLAZIKENITE"
#define ITEM_SWAMPERTITE "SWAMPERTITE"
#define ITEM_GARDEVOIRITE "GARDEVOIRITE"
#define ITEM_SABLENITE "SABLENITE"
#define ITEM_MAWILITE "MAWILITE"
#define ITEM_AGGRONITE "AGGRONITE"
#define ITEM_MEDICHAMITE "MEDICHAMITE"
#define ITEM_MANECTITE "MANECTITE"
#define ITEM_SHARPEDONITE "SHARPEDONITE"
#define ITEM_CAMERUPTITE "CAMERUPTITE"
#define ITEM_ALTARIANITE "ALTARIANITE"
#define ITEM_BANETTITE "BANETTITE"
#define ITEM_ABSOLITE "ABSOLITE"
#define ITEM_GLALITITE "GLALITITE"
#define ITEM_SALAMENCITE "SALAMENCITE"
#define ITEM_METAGROSSITE "METAGROSSITE"
#define ITEM_LATIASITE "LATIASITE"
#define ITEM_LATIOSITE "LATIOSITE"
#define ITEM_LOPUNNITE "LOPUNNITE"
#define ITEM_GARCHOMPITE "GARCHOMPITE"
#define ITEM_LUCARIONITE "LUCARIONITE"
#define ITEM_ABOMASITE "ABOMASITE"
#define ITEM_GALLADITE "GALLADITE"
#define ITEM_AUDINITE "AUDINITE"
#define ITEM_DIANCITE "DIANCITE"

// Type-Resist + New Berries
#define ITEM_OCCA_BERRY "OCCA_BERRY"
#define ITEM_PASSHO_BERRY "PASSHO_BERRY"
#define ITEM_WACAN_BERRY "WACAN_BERRY"
#define ITEM_RINDO_BERRY "RINDO_BERRY"
#define ITEM_YACHE_BERRY "YACHE_BERRY"
#define ITEM_CHOPLE_BERRY "CHOPLE_BERRY"
#define ITEM_KEBIA_BERRY "KEBIA_BERRY"
#define ITEM_SHUCA_BERRY "SHUCA_BERRY"
#define ITEM_COBA_BERRY "COBA_BERRY"
#define ITEM_PAYAPA_BERRY "PAYAPA_BERRY"
#define ITEM_TANGA_BERRY "TANGA_BERRY"
#define ITEM_CHARTI_BERRY "CHARTI_BERRY"
#define ITEM_KASIB_BERRY "KASIB_BERRY"
#define ITEM_HABAN_BERRY "HABAN_BERRY"
#define ITEM_COLBUR_BERRY "COLBUR_BERRY"
#define ITEM_BABIRI_BERRY "BABIRI_BERRY"
#define ITEM_CHILAN_BERRY "CHILAN_BERRY"
#define ITEM_MICLE_BERRY "MICLE_BERRY"
#define ITEM_CUSTAP_BERRY "CUSTAP_BERRY"
#define ITEM_JABOCA_BERRY "JABOCA_BERRY"
#define ITEM_ROWAP_BERRY "ROWAP_BERRY"
#define ITEM_ROSELI_BERRY "ROSELI_BERRY"
#define ITEM_KEE_BERRY "KEE_BERRY"
#define ITEM_MARANGA_BERRY "MARANGA_BERRY"

// New Poke Balls
#define ITEM_PARK_BALL "PARK_BALL"
#define ITEM_CHERISH_BALL "CHERISH_BALL"
#define ITEM_DUSK_BALL "DUSK_BALL"
#define ITEM_HEAL_BALL "HEAL_BALL"
#define ITEM_QUICK_BALL "QUICK_BALL"
#define ITEM_FAST_BALL "FAST_BALL"
#define ITEM_LEVEL_BALL "LEVEL_BALL"
#define ITEM_LURE_BALL "LURE_BALL"
#define ITEM_HEAVY_BALL "HEAVY_BALL"
#define ITEM_LOVE_BALL "LOVE_BALL"
#define ITEM_FRIEND_BALL "FRIEND_BALL"
#define ITEM_MOON_BALL "MOON_BALL"
#define ITEM_SPORT_BALL "SPORT_BALL"
#define ITEM_BEAST_BALL "BEAST_BALL"
#define ITEM_DREAM_BALL "DREAM_BALL"

// Genesect Drives
#define ITEM_BURN_DRIVE "BURN_DRIVE"
#define ITEM_DOUSE_DRIVE "DOUSE_DRIVE"
#define ITEM_SHOCK_DRIVE "SHOCK_DRIVE"
#define ITEM_CHILL_DRIVE "CHILL_DRIVE"

// Silvally Memories
#define ITEM_FIGHTING_MEMORY "FIGHTING_MEMORY"
#define ITEM_FLYING_MEMORY "FLYING_MEMORY"
#define ITEM_POISON_MEMORY "POISON_MEMORY"
#define ITEM_GROUND_MEMORY "GROUND_MEMORY"
#define ITEM_ROCK_MEMORY "ROCK_MEMORY"
#define ITEM_BUG_MEMORY "BUG_MEMORY"
#define ITEM_GHOST_MEMORY "GHOST_MEMORY"
#define ITEM_STEEL_MEMORY "STEEL_MEMORY"
#define ITEM_FIRE_MEMORY "FIRE_MEMORY"
#define ITEM_WATER_MEMORY "WATER_MEMORY"
#define ITEM_GRASS_MEMORY "GRASS_MEMORY"
#define ITEM_ELECTRIC_MEMORY "ELECTRIC_MEMORY"
#define ITEM_PSYCHIC_MEMORY "PSYCHIC_MEMORY"
#define ITEM_ICE_MEMORY "ICE_MEMORY"
#define ITEM_DRAGON_MEMORY "DRAGON_MEMORY"
#define ITEM_DARK_MEMORY "DARK_MEMORY"
#define ITEM_FAIRY_MEMORY "FAIRY_MEMORY"

// Wings
#define ITEM_HEALTH_WING "HEALTH_WING"
#define ITEM_MUSCLE_WING "MUSCLE_WING"
#define ITEM_RESIST_WING "RESIST_WING"
#define ITEM_GENIUS_WING "GENIUS_WING"
#define ITEM_CLEVER_WING "CLEVER_WING"
#define ITEM_SWIFT_WING "SWIFT_WING"
#define ITEM_PRETTY_WING "PRETTY_WING"

// Random Normal Items
#define ITEM_ODD_KEYSTONE "ODD_KEYSTONE"
#define ITEM_BOTTLE_CAP "BOTTLE_CAP"
#define ITEM_GOLD_BOTTLE_CAP "GOLD_BOTTLE_CAP"
#define ITEM_ABILITY_CAPSULE "ABILITY_CAPSULE"
#define ITEM_DREAM_MIST "DREAM_MIST"
#define ITEM_WISHING_PIECE "WISHING_PIECE"
#define ITEM_MAX_POWDER "MAX_POWDER"

// Nectars
#define ITEM_RED_NECTAR "RED_NECTAR"
#define ITEM_YELLOW_NECTAR "YELLOW_NECTAR"
#define ITEM_PINK_NECTAR "PINK_NECTAR"
#define ITEM_PURPLE_NECTAR "PURPLE_NECTAR"

// Evolution Items
#define ITEM_LINK_STONE "LINK_STONE"
#define ITEM_DUSK_STONE "DUSK_STONE"
#define ITEM_DAWN_STONE "DAWN_STONE"
#define ITEM_SHINY_STONE "SHINY_STONE"
#define ITEM_OVAL_STONE "OVAL_STONE"
#define ITEM_ICE_STONE "ICE_STONE"

#define ITEM_PROTECTOR "PROTECTOR"
#define ITEM_MAGMARIZER "MAGMARIZER"
#define ITEM_PRISM_SCALE "PRISM_SCALE"
#define ITEM_SACHET "SACHET"
#define ITEM_WHIPPED_DREAM "WHIPPED_DREAM"
#define ITEM_RAZOR_CLAW "RAZOR_CLAW"
#define ITEM_RAZOR_FANG "RAZOR_FANG"
#define ITEM_REAPER_CLOTH "REAPER_CLOTH"
#define ITEM_DUBIOUS_DISC "DUBIOUS_DISC"
#define ITEM_ELECTIRIZER "ELECTIRIZER"
#define ITEM_SWEET_APPLE "SWEET_APPLE"
#define ITEM_TART_APPLE "TART_APPLE"
#define ITEM_CRACKED_POT "CRACKED_POT"
#define ITEM_CHIPPED_POT "CHIPPED_POT"
#define ITEM_STRAWBERRY_SWEET "STRAWBERRY_SWEET"
#define ITEM_BERRY_SWEET "BERRY_SWEET"
#define ITEM_LOVE_SWEET "LOVE_SWEET"
#define ITEM_CLOVER_SWEET "CLOVER_SWEET"
#define ITEM_FLOWER_SWEET "FLOWER_SWEET"
#define ITEM_RIBBON_SWEET "RIBBON_SWEET"
#define ITEM_STAR_SWEET "STAR_SWEET"
#define ITEM_GALARICA_CUFF "GALARICA_CUFF"
#define ITEM_GALARICA_WREATH "GALARICA_WREATH"
#define ITEM_BLACK_AUGURITE "BLACK_AUGURITE"
#define ITEM_PEAT_BLOCK "PEAT_BLOCK"
#define ITEM_HISUI_ROCK "HISUI_ROCK"

// New Key Items
#define ITEM_GRACIDEA "GRACIDEA"
#define ITEM_DNA_SPLICERS "DNA_SPLICERS"
#define ITEM_REVEAL_GLASS "REVEAL_GLASS"
#define ITEM_PRISON_BOTTLE "PRISON_BOTTLE"
#define ITEM_REINS_OF_UNITY "REINS_OF_UNITY"

#define ITEM_OVAL_CHARM "OVAL_CHARM"
#define ITEM_SHINY_CHARM "SHINY_CHARM"
#define ITEM_CATCHING_CHARM "CATCHING_CHARM"
#define ITEM_RAINBOW_WING "RAINBOW_WING"
#define ITEM_SILVER_WING "SILVER_WING"
#define ITEM_MAGMA_STONE "MAGMA_STONE"
#define ITEM_N_SOLARIZER "N_SOLARIZER"
#define ITEM_N_LUNARIZER "N_LUNARIZER"
#define ITEM_SUN_FLUTE "SUN_FLUTE"
#define ITEM_MOON_FLUTE "MOON_FLUTE"
#define ITEM_LIGHT_STONE "LIGHT_STONE"
#define ITEM_DARK_STONE "DARK_STONE"

#define ITEM_DYNAMAX_BAND "DYNAMAX_BAND"

// Relic Items
#define ITEM_RELIC_COPPER "RELIC_COPPER"
#define ITEM_RELIC_SILVER "RELIC_SILVER"
#define ITEM_RELIC_GOLD "RELIC_GOLD"
#define ITEM_RELIC_VASE "RELIC_VASE"
#define ITEM_RELIC_BAND "RELIC_BAND"
#define ITEM_RELIC_STATUE "RELIC_STATUE"
#define ITEM_RELIC_CROWN "RELIC_CROWN"

// Z-Crystals
enum
{
    ITEM_NORMALIUM_Z = 0x29E, // All items after this will be 0x29E + 1, 0x29E + 2...
    ITEM_FIGHTINIUM_Z,        // 0x29F //Put the Z-Crystals in order
    ITEM_FLYINIUM_Z,          // 0x2A0
    ITEM_POISONIUM_Z,         // 0x2A1
    ITEM_GROUNDIUM_Z,         // 0x2A2
    ITEM_ROCKIUM_Z,           // 0x2A3
    ITEM_BUGINIUM_Z,          // 0x2A4
    ITEM_GHOSTIUM_Z,          // 0x2A5
    ITEM_STEELIUM_Z,          // 0x2A6
    ITEM_FIRIUM_Z,            // 0x2A7
    ITEM_WATERIUM_Z,          // 0x2A8
    ITEM_GRASSIUM_Z,          // 0x2A9
    ITEM_ELECTRIUM_Z,         // 0x2AA
    ITEM_PSYCHIUM_Z,          // 0x2AB
    ITEM_ICIUM_Z,             // 0x2AC
    ITEM_DRAGONIUM_Z,         // 0x2AD
    ITEM_DARKINIUM_Z,         // 0x2AE
    ITEM_FAIRIUM_Z,           // 0x2AF
    ITEM_ALORAICHIUM_Z,       // 0x2B0
    ITEM_DECIDIUM_Z,          // 0x2B1
    ITEM_EEVIUM_Z,            // 0x2B2
    ITEM_INCINIUM_Z,          // 0x2B3
    ITEM_KOMMONIUM_Z,         // 0x2B4
    ITEM_LUNALIUM_Z,          // 0x2B5
    ITEM_LYCANIUM_Z,          // 0x2B6
    ITEM_MARSHADIUM_Z,        // 0x2B7
    ITEM_MEWNIUM_Z,           // 0x2B8
    ITEM_MIMIKIUM_Z,          // 0x2B9
    ITEM_PIKANIUM_Z,          // 0x2BA
    ITEM_PIKASHUNIUM_Z,       // 0x2BB
    ITEM_PRIMARIUM_Z,         // 0x2BC
    ITEM_SNORLIUM_Z,          // 0x2BD
    ITEM_SOLGANIUM_Z,         // 0x2BE
    ITEM_TAPUNIUM_Z,          // 0x2BF
};

// Sword & Shield Hold Items
#define ITEM_EJECT_PACK "EJECT_PACK"
#define ITEM_ROOM_SERVICE "ROOM_SERVICE"
#define ITEM_BLUNDER_POLICY "BLUNDER_POLICY"
#define ITEM_HEAVY_DUTY_BOOTS "HEAVY_DUTY_BOOTS"
#define ITEM_UTILITY_UMBRELLA "UTILITY_UMBRELLA"
#define ITEM_THROAT_SPRAY "THROAT_SPRAY"
#define ITEM_RUSTED_SWORD "RUSTED_SWORD"
#define ITEM_RUSTED_SHIELD "RUSTED_SHIELD"

#define ITEMS_COUNT (ITEM_HISUI_ROCK +

// For "For" Pokemon Unbound
#ifdef UNBOUND

#undef ITEM_ENIGMA_BERRY

#define ITEM_ODDISH_LEAF "ODDISH_LEAF"
#define ITEM_ENIGMA_BERRY "ENIGMA_BERRY"
#define ITEM_DOWSING_MACHINE "DOWSING_MACHINE"
#define ITEM_GRUBBY_HANKY "GRUBBY_HANKY"
#define ITEM_UNIFORM "UNIFORM"
#define ITEM_FASHION_CASE "FASHION_CASE"
#define ITEM_POKE_BALL_KEY_ITEM "POKE_BALL_KEY_ITEM"
#define ITEM_KEY_CARD_1 "KEY_CARD_1"
#define ITEM_KEY_CARD_2 "KEY_CARD_2"
#define ITEM_KEY_CARD_3 "KEY_CARD_3"
#define ITEM_QUEST_LOG "QUEST_LOG"
#define ITEM_SMELLY_SOCKS "SMELLY_SOCKS"
#define ITEM_COSTUME_BOX "COSTUME_BOX"

#define ITEM_MEGA_CUFF "MEGA_CUFF"
#define ITEM_MEGA_BONNET "MEGA_BONNET"
#define ITEM_MEGA_EARING "MEGA_EARING"
#define ITEM_MEGA_CHARM "MEGA_CHARM"
#define ITEM_MEGA_BRACELET "MEGA_BRACELET"
#define ITEM_MEGA_ANKLET "MEGA_ANKLET"
#define ITEM_MEGA_PENDANT "MEGA_PENDANT"

// TMs & HMs
enum
{
    ITEM_TM01_FOCUS_PUNCH = 0x121,
    ITEM_TM02_DRAGON_CLAW,
    ITEM_TM03_WATER_PULSE,
    ITEM_TM04_CALM_MIND,
    ITEM_TM05_ROAR,
    ITEM_TM06_TOXIC,
    ITEM_TM07_HAIL,
    ITEM_TM08_BULK_UP,
    ITEM_TM09_BULLET_SEED,
    ITEM_TM10_HIDDEN_POWER,
    ITEM_TM11_SUNNY_DAY,
    ITEM_TM12_TAUNT,
    ITEM_TM13_ICE_BEAM,
    ITEM_TM14_BLIZZARD,
    ITEM_TM15_HYPER_BEAM,
    ITEM_TM16_LIGHT_SCREEN,
    ITEM_TM17_PROTECT,
    ITEM_TM18_RAIN_DANCE,
    ITEM_TM19_GIGA_DRAIN,
    ITEM_TM20_SAFEGUARD,
    ITEM_TM21_FRUSTRATION,
    ITEM_TM22_SOLARBEAM,
    ITEM_TM23_IRON_TAIL,
    ITEM_TM24_THUNDERBOLT,
    ITEM_TM25_THUNDER,
    ITEM_TM26_EARTHQUAKE,
    ITEM_TM27_RETURN,
    ITEM_TM28_DIG,
    ITEM_TM29_PSYCHIC,
    ITEM_TM30_SHADOW_BALL,
    ITEM_TM31_BRICK_BREAK,
    ITEM_TM32_DOUBLE_TEAM,
    ITEM_TM33_REFLECT,
    ITEM_TM34_SHOCK_WAVE,
    ITEM_TM35_FLAMETHROWER,
    ITEM_TM36_SLUDGE_BOMB,
    ITEM_TM37_SANDSTORM,
    ITEM_TM38_FIRE_BLAST,
    ITEM_TM39_ROCK_TOMB,
    ITEM_TM40_AERIAL_ACE,
    ITEM_TM41_TORMENT,
    ITEM_TM42_FACADE,
    ITEM_TM43_SECRET_POWER,
    ITEM_TM44_REST,
    ITEM_TM45_ATTRACT,
    ITEM_TM46_THIEF,
    ITEM_TM47_STEEL_WING,
    ITEM_TM48_SKILL_SWAP,
    ITEM_TM49_LEECH_FANG,
    ITEM_TM50_OVERHEAT,
    ITEM_TM51_ROOST,
    ITEM_TM52_FOCUS_BLAST,
    ITEM_TM53_ENERGY_BALL,
    ITEM_TM54_FALSE_SWIPE,
    ITEM_TM55_BRINE,
    ITEM_TM56_HONE_CLAWS,
    ITEM_TM57_CHARGE_BEAM,
    ITEM_TM58_ENDURE,
    ITEM_TM59_DRAGON_PULSE = 0x177,
    ITEM_TM60_DRAIN_PUNCH,
    ITEM_TM61_WILL_O_WISP,
    ITEM_TM62_SILVER_WIND,
    ITEM_TM63_VENOSHOCK,
    ITEM_TM64_EXPLOSION,
    ITEM_TM65_SHADOW_CLAW,
    ITEM_TM66_PAYBACK,
    ITEM_TM67_RECYCLE,
    ITEM_TM68_GIGA_IMPACT,
    ITEM_TM69_ROCK_POLISH,
    ITEM_TM70_FLASH,
    ITEM_TM71_STONE_EDGE,
    ITEM_TM72_AVALANCHE,
    ITEM_TM73_THUNDER_WAVE,
    ITEM_TM74_GYRO_BALL,
    ITEM_TM75_SWORDS_DANCE,
    ITEM_TM76_STEALTH_ROCK,
    ITEM_TM77_FLAME_CHARGE,
    ITEM_TM78_LOW_SWEEP,
    ITEM_TM79_DARK_PULSE,
    ITEM_TM80_ROCK_SLIDE,
    ITEM_TM81_X_SCISSOR,
    ITEM_TM82_SLEEP_TALK,
    ITEM_TM83_SCALD,
    ITEM_TM84_POISON_JAB,
    ITEM_TM85_DREAM_EATER,
    ITEM_TM86_GRASS_KNOT,
    ITEM_TM87_SWAGGER,
    ITEM_TM88_PLUCK,
    ITEM_TM89_U_TURN,
    ITEM_TM90_SUBSTITUTE,
    ITEM_TM91_FLASH_CANNON,
    ITEM_TM92_VOLT_SWITCH,
    ITEM_TM93_DRAGON_TAIL,
    ITEM_TM94_INCINERATE,
    ITEM_TM95_STRUGGLE_BUG,
    ITEM_TM96_BULLDOZE,
    ITEM_TM97_FROST_BREATH,
    ITEM_TM98_WORK_UP,
    ITEM_TM99_WILD_CHARGE,
    ITEM_TM100_INFESTATION,
    ITEM_TM101_POWER_UP_PUNCH,
    ITEM_TM102_DAZZLING_GLEAM,
    ITEM_TM103_SLUDGE_WAVE,
    ITEM_TM104_PSYSHOCK,
    ITEM_TM105_BRUTAL_SWING,
    ITEM_TM106_SMART_STRIKE,
    ITEM_TM107_ACROBATICS,
    ITEM_TM108_SNARL,
    ITEM_TM109_DEFOG,
    ITEM_TM110_DRAINING_KISS,
    ITEM_TM111_SMACK_DOWN,
    ITEM_TM112_ROUND,
    ITEM_TM113_ECHOED_VOICE,
    ITEM_TM114_NATURAL_GIFT,
    ITEM_TM115_QUASH,
    ITEM_TM116_TRICK_ROOM,
    ITEM_TM117_FLING,
    ITEM_TM118_AURORA_VEIL,
    ITEM_TM119_SKY_DROP,
    ITEM_TM120_NATURE_POWER,
    ITEM_HM01_CUT,
    ITEM_HM02_FLY,
    ITEM_HM03_SURF,
    ITEM_HM04_STRENGTH,
    ITEM_HM05_DIVE,
    ITEM_HM06_ROCK_SMASH,
    ITEM_HM07_WATERFALL,
    ITEM_HM08_ROCK_CLIMB,
};

#endif

// Emerald
#define FIRST_BERRY_INDEX "_BERRY_INDEX"
#define LAST_BERRY_INDEX "BERRY_INDEX"
#define ITEM_TO_BERRY(itemId) (((itemId - FIRST_BERRY_INDEX) + 1))

#define NUM_TECHNICAL_MACHINES "ECHNICAL_MACHINES"
#define NUM_HIDDEN_MACHINES "IDDEN_MACHINES"

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_0B2)

// POCKETS
#define POCKET_ITEMS "T_ITEMS"
#define POCKET_KEY_ITEMS "T_KEY_ITEMS"
#define POCKET_POKE_BALLS "T_POKE_BALLS"
#define POCKET_TM_CASE "T_TM_CASE"
#define POCKET_BERRY_POUCH "T_BERRY_POUCH"