# first line is the "TUTOR\d{2,3}: {pokemon name}"
import re
import glob
import json

pokemon_names = [
    "NONE",
    "BULBASAUR",
    "IVYSAUR",
    "VENUSAUR",
    "CHARMANDER",
    "CHARMELEON",
    "CHARIZARD",
    "SQUIRTLE",
    "WARTORTLE",
    "BLASTOISE",
    "CATERPIE",
    "METAPOD",
    "BUTTERFREE",
    "WEEDLE",
    "KAKUNA",
    "BEEDRILL",
    "PIDGEY",
    "PIDGEOTTO",
    "PIDGEOT",
    "RATTATA",
    "RATICATE",
    "SPEAROW",
    "FEAROW",
    "EKANS",
    "ARBOK",
    "PIKACHU",
    "RAICHU",
    "SANDSHREW",
    "SANDSLASH",
    "NIDORAN_F",
    "NIDORINA",
    "NIDOQUEEN",
    "NIDORAN_M",
    "NIDORINO",
    "NIDOKING",
    "CLEFAIRY",
    "CLEFABLE",
    "VULPIX",
    "NINETALES",
    "JIGGLYPUFF",
    "WIGGLYTUFF",
    "ZUBAT",
    "GOLBAT",
    "ODDISH",
    "GLOOM",
    "VILEPLUME",
    "PARAS",
    "PARASECT",
    "VENONAT",
    "VENOMOTH",
    "DIGLETT",
    "DUGTRIO",
    "MEOWTH",
    "PERSIAN",
    "PSYDUCK",
    "GOLDUCK",
    "MANKEY",
    "PRIMEAPE",
    "GROWLITHE",
    "ARCANINE",
    "POLIWAG",
    "POLIWHIRL",
    "POLIWRATH",
    "ABRA",
    "KADABRA",
    "ALAKAZAM",
    "MACHOP",
    "MACHOKE",
    "MACHAMP",
    "BELLSPROUT",
    "WEEPINBELL",
    "VICTREEBEL",
    "TENTACOOL",
    "TENTACRUEL",
    "GEODUDE",
    "GRAVELER",
    "GOLEM",
    "PONYTA",
    "RAPIDASH",
    "SLOWPOKE",
    "SLOWBRO",
    "MAGNEMITE",
    "MAGNETON",
    "FARFETCHD",
    "DODUO",
    "DODRIO",
    "SEEL",
    "DEWGONG",
    "GRIMER",
    "MUK",
    "SHELLDER",
    "CLOYSTER",
    "GASTLY",
    "HAUNTER",
    "GENGAR",
    "ONIX",
    "DROWZEE",
    "HYPNO",
    "KRABBY",
    "KINGLER",
    "VOLTORB",
    "ELECTRODE",
    "EXEGGCUTE",
    "EXEGGUTOR",
    "CUBONE",
    "MAROWAK",
    "HITMONLEE",
    "HITMONCHAN",
    "LICKITUNG",
    "KOFFING",
    "WEEZING",
    "RHYHORN",
    "RHYDON",
    "CHANSEY",
    "TANGELA",
    "KANGASKHAN",
    "HORSEA",
    "SEADRA",
    "GOLDEEN",
    "SEAKING",
    "STARYU",
    "STARMIE",
    "MR_MIME",
    "SCYTHER",
    "JYNX",
    "ELECTABUZZ",
    "MAGMAR",
    "PINSIR",
    "TAUROS",
    "MAGIKARP",
    "GYARADOS",
    "LAPRAS",
    "DITTO",
    "EEVEE",
    "VAPOREON",
    "JOLTEON",
    "FLAREON",
    "PORYGON",
    "OMANYTE",
    "OMASTAR",
    "KABUTO",
    "KABUTOPS",
    "AERODACTYL",
    "SNORLAX",
    "ARTICUNO",
    "ZAPDOS",
    "MOLTRES",
    "DRATINI",
    "DRAGONAIR",
    "DRAGONITE",
    "MEWTWO",
    "MEW",
    "CHIKORITA",
    "BAYLEEF",
    "MEGANIUM",
    "CYNDAQUIL",
    "QUILAVA",
    "TYPHLOSION",
    "TOTODILE",
    "CROCONAW",
    "FERALIGATR",
    "SENTRET",
    "FURRET",
    "HOOTHOOT",
    "NOCTOWL",
    "LEDYBA",
    "LEDIAN",
    "SPINARAK",
    "ARIADOS",
    "CROBAT",
    "CHINCHOU",
    "LANTURN",
    "PICHU",
    "CLEFFA",
    "IGGLYBUFF",
    "TOGEPI",
    "TOGETIC",
    "NATU",
    "XATU",
    "MAREEP",
    "FLAAFFY",
    "AMPHAROS",
    "BELLOSSOM",
    "MARILL",
    "AZUMARILL",
    "SUDOWOODO",
    "POLITOED",
    "HOPPIP",
    "SKIPLOOM",
    "JUMPLUFF",
    "AIPOM",
    "SUNKERN",
    "SUNFLORA",
    "YANMA",
    "WOOPER",
    "QUAGSIRE",
    "ESPEON",
    "UMBREON",
    "MURKROW",
    "SLOWKING",
    "MISDREAVUS",
    "UNOWN",
    "WOBBUFFET",
    "GIRAFARIG",
    "PINECO",
    "FORRETRESS",
    "DUNSPARCE",
    "GLIGAR",
    "STEELIX",
    "SNUBBULL",
    "GRANBULL",
    "QWILFISH",
    "SCIZOR",
    "SHUCKLE",
    "HERACROSS",
    "SNEASEL",
    "TEDDIURSA",
    "URSARING",
    "SLUGMA",
    "MAGCARGO",
    "SWINUB",
    "PILOSWINE",
    "CORSOLA",
    "REMORAID",
    "OCTILLERY",
    "DELIBIRD",
    "MANTINE",
    "SKARMORY",
    "HOUNDOUR",
    "HOUNDOOM",
    "KINGDRA",
    "PHANPY",
    "DONPHAN",
    "PORYGON2",
    "STANTLER",
    "SMEARGLE",
    "TYROGUE",
    "HITMONTOP",
    "SMOOCHUM",
    "ELEKID",
    "MAGBY",
    "MILTANK",
    "BLISSEY",
    "RAIKOU",
    "ENTEI",
    "SUICUNE",
    "LARVITAR",
    "PUPITAR",
    "TYRANITAR",
    "LUGIA",
    "HO_OH",
    "CELEBI",
    "MANAPHY_EGG",
    "MISSINGNO",
    "TREECKO",
    "GROVYLE",
    "SCEPTILE",
    "TORCHIC",
    "COMBUSKEN",
    "BLAZIKEN",
    "MUDKIP",
    "MARSHTOMP",
    "SWAMPERT",
    "POOCHYENA",
    "MIGHTYENA",
    "ZIGZAGOON",
    "LINOONE",
    "WURMPLE",
    "SILCOON",
    "BEAUTIFLY",
    "CASCOON",
    "DUSTOX",
    "LOTAD",
    "LOMBRE",
    "LUDICOLO",
    "SEEDOT",
    "NUZLEAF",
    "SHIFTRY",
    "NINCADA",
    "NINJASK",
    "SHEDINJA",
    "TAILLOW",
    "SWELLOW",
    "SHROOMISH",
    "BRELOOM",
    "SPINDA",
    "WINGULL",
    "PELIPPER",
    "SURSKIT",
    "MASQUERAIN",
    "WAILMER",
    "WAILORD",
    "SKITTY",
    "DELCATTY",
    "KECLEON",
    "BALTOY",
    "CLAYDOL",
    "NOSEPASS",
    "TORKOAL",
    "SABLEYE",
    "BARBOACH",
    "WHISCASH",
    "LUVDISC",
    "CORPHISH",
    "CRAWDAUNT",
    "FEEBAS",
    "MILOTIC",
    "CARVANHA",
    "SHARPEDO",
    "TRAPINCH",
    "VIBRAVA",
    "FLYGON",
    "MAKUHITA",
    "HARIYAMA",
    "ELECTRIKE",
    "MANECTRIC",
    "NUMEL",
    "CAMERUPT",
    "SPHEAL",
    "SEALEO",
    "WALREIN",
    "CACNEA",
    "CACTURNE",
    "SNORUNT",
    "GLALIE",
    "LUNATONE",
    "SOLROCK",
    "AZURILL",
    "SPOINK",
    "GRUMPIG",
    "PLUSLE",
    "MINUN",
    "MAWILE",
    "MEDITITE",
    "MEDICHAM",
    "SWABLU",
    "ALTARIA",
    "WYNAUT",
    "DUSKULL",
    "DUSCLOPS",
    "ROSELIA",
    "SLAKOTH",
    "VIGOROTH",
    "SLAKING",
    "GULPIN",
    "SWALOT",
    "TROPIUS",
    "WHISMUR",
    "LOUDRED",
    "EXPLOUD",
    "CLAMPERL",
    "HUNTAIL",
    "GOREBYSS",
    "ABSOL",
    "SHUPPET",
    "BANETTE",
    "SEVIPER",
    "ZANGOOSE",
    "RELICANTH",
    "ARON",
    "LAIRON",
    "AGGRON",
    "CASTFORM",
    "VOLBEAT",
    "ILLUMISE",
    "LILEEP",
    "CRADILY",
    "ANORITH",
    "ARMALDO",
    "RALTS",
    "KIRLIA",
    "GARDEVOIR",
    "BAGON",
    "SHELGON",
    "SALAMENCE",
    "BELDUM",
    "METANG",
    "METAGROSS",
    "REGIROCK",
    "REGICE",
    "REGISTEEL",
    "KYOGRE",
    "GROUDON",
    "RAYQUAZA",
    "LATIAS",
    "LATIOS",
    "JIRACHI",
    "DEOXYS",
    "CHIMECHO",
    "EGG",
    "UNOWN_B",
    "UNOWN_C",
    "UNOWN_D",
    "UNOWN_E",
    "UNOWN_F",
    "UNOWN_G",
    "UNOWN_H",
    "UNOWN_I",
    "UNOWN_J",
    "UNOWN_K",
    "UNOWN_L",
    "UNOWN_M",
    "UNOWN_N",
    "UNOWN_O",
    "UNOWN_P",
    "UNOWN_Q",
    "UNOWN_R",
    "UNOWN_S",
    "UNOWN_T",
    "UNOWN_U",
    "UNOWN_V",
    "UNOWN_W",
    "UNOWN_X",
    "UNOWN_Y",
    "UNOWN_Z",
    "UNOWN_EXCLAMATION",
    "UNOWN_QUESTION",
    "TURTWIG",
    "GROTLE",
    "TORTERRA",
    "CHIMCHAR",
    "MONFERNO",
    "INFERNAPE",
    "PIPLUP",
    "PRINPLUP",
    "EMPOLEON",
    "STARLY",
    "STARAVIA",
    "STARAPTOR",
    "BIDOOF",
    "BIBAREL",
    "KRICKETOT",
    "KRICKETUNE",
    "SHINX",
    "LUXIO",
    "LUXRAY",
    "BUDEW",
    "ROSERADE",
    "CRANIDOS",
    "RAMPARDOS",
    "SHIELDON",
    "BASTIODON",
    "BURMY",
    "WORMADAM",
    "MOTHIM",
    "COMBEE",
    "VESPIQUEN",
    "PACHIRISU",
    "BUIZEL",
    "FLOATZEL",
    "CHERUBI",
    "CHERRIM",
    "SHELLOS",
    "GASTRODON",
    "AMBIPOM",
    "DRIFLOON",
    "DRIFBLIM",
    "BUNEARY",
    "LOPUNNY",
    "MISMAGIUS",
    "HONCHKROW",
    "GLAMEOW",
    "PURUGLY",
    "CHINGLING",
    "STUNKY",
    "SKUNTANK",
    "BRONZOR",
    "BRONZONG",
    "BONSLY",
    "MIME_JR",
    "HAPPINY",
    "CHATOT",
    "SPIRITOMB",
    "GIBLE",
    "GABITE",
    "GARCHOMP",
    "MUNCHLAX",
    "RIOLU",
    "LUCARIO",
    "HIPPOPOTAS",
    "HIPPOWDON",
    "SKORUPI",
    "DRAPION",
    "CROAGUNK",
    "TOXICROAK",
    "CARNIVINE",
    "FINNEON",
    "LUMINEON",
    "MANTYKE",
    "SNOVER",
    "ABOMASNOW",
    "WEAVILE",
    "MAGNEZONE",
    "LICKILICKY",
    "RHYPERIOR",
    "TANGROWTH",
    "ELECTIVIRE",
    "MAGMORTAR",
    "TOGEKISS",
    "YANMEGA",
    "LEAFEON",
    "GLACEON",
    "GLISCOR",
    "MAMOSWINE",
    "PORYGON_Z",
    "GALLADE",
    "PROBOPASS",
    "DUSKNOIR",
    "FROSLASS",
    "ROTOM",
    "UXIE",
    "MESPRIT",
    "AZELF",
    "DIALGA",
    "PALKIA",
    "HEATRAN",
    "REGIGIGAS",
    "GIRATINA",
    "CRESSELIA",
    "PHIONE",
    "MANAPHY",
    "DARKRAI",
    "SHAYMIN",
    "ARCEUS",
    "VICTINI",
    "SNIVY",
    "SERVINE",
    "SERPERIOR",
    "TEPIG",
    "PIGNITE",
    "EMBOAR",
    "OSHAWOTT",
    "DEWOTT",
    "SAMUROTT",
    "PATRAT",
    "WATCHOG",
    "LILLIPUP",
    "HERDIER",
    "STOUTLAND",
    "PURRLOIN",
    "LIEPARD",
    "PANSAGE",
    "SIMISAGE",
    "PANSEAR",
    "SIMISEAR",
    "PANPOUR",
    "SIMIPOUR",
    "MUNNA",
    "MUSHARNA",
    "PIDOVE",
    "TRANQUILL",
    "UNFEZANT",
    "BLITZLE",
    "ZEBSTRIKA",
    "ROGGENROLA",
    "BOLDORE",
    "GIGALITH",
    "WOOBAT",
    "SWOOBAT",
    "DRILBUR",
    "EXCADRILL",
    "AUDINO",
    "TIMBURR",
    "GURDURR",
    "CONKELDURR",
    "TYMPOLE",
    "PALPITOAD",
    "SEISMITOAD",
    "THROH",
    "SAWK",
    "SEWADDLE",
    "SWADLOON",
    "LEAVANNY",
    "VENIPEDE",
    "WHIRLIPEDE",
    "SCOLIPEDE",
    "COTTONEE",
    "WHIMSICOTT",
    "PETILIL",
    "LILLIGANT",
    "BASCULIN_RED",
    "SANDILE",
    "KROKOROK",
    "KROOKODILE",
    "DARUMAKA",
    "DARMANITAN",
    "MARACTUS",
    "DWEBBLE",
    "CRUSTLE",
    "SCRAGGY",
    "SCRAFTY",
    "SIGILYPH",
    "YAMASK",
    "COFAGRIGUS",
    "TIRTOUGA",
    "CARRACOSTA",
    "ARCHEN",
    "ARCHEOPS",
    "TRUBBISH",
    "GARBODOR",
    "ZORUA",
    "ZOROARK",
    "MINCCINO",
    "CINCCINO",
    "GOTHITA",
    "GOTHORITA",
    "GOTHITELLE",
    "SOLOSIS",
    "DUOSION",
    "REUNICLUS",
    "DUCKLETT",
    "SWANNA",
    "VANILLITE",
    "VANILLISH",
    "VANILLUXE",
    "DEERLING",
    "SAWSBUCK",
    "EMOLGA",
    "KARRABLAST",
    "ESCAVALIER",
    "FOONGUS",
    "AMOONGUSS",
    "FRILLISH",
    "JELLICENT",
    "ALOMOMOLA",
    "JOLTIK",
    "GALVANTULA",
    "FERROSEED",
    "FERROTHORN",
    "KLINK",
    "KLANG",
    "KLINKLANG",
    "TYNAMO",
    "EELEKTRIK",
    "EELEKTROSS",
    "ELGYEM",
    "BEHEEYEM",
    "LITWICK",
    "LAMPENT",
    "CHANDELURE",
    "AXEW",
    "FRAXURE",
    "HAXORUS",
    "CUBCHOO",
    "BEARTIC",
    "CRYOGONAL",
    "SHELMET",
    "ACCELGOR",
    "STUNFISK",
    "MIENFOO",
    "MIENSHAO",
    "DRUDDIGON",
    "GOLETT",
    "GOLURK",
    "PAWNIARD",
    "BISHARP",
    "BOUFFALANT",
    "RUFFLET",
    "BRAVIARY",
    "VULLABY",
    "MANDIBUZZ",
    "HEATMOR",
    "DURANT",
    "DEINO",
    "ZWEILOUS",
    "HYDREIGON",
    "LARVESTA",
    "VOLCARONA",
    "COBALION",
    "TERRAKION",
    "VIRIZION",
    "TORNADUS",
    "THUNDURUS",
    "RESHIRAM",
    "ZEKROM",
    "LANDORUS",
    "KYUREM",
    "KELDEO",
    "MELOETTA",
    "GENESECT",
    "UNFEZANT_F",
    "FRILLISH_F",
    "JELLICENT_F",
    "SHADOW_WARRIOR",
    "BURMY_SANDY",
    "BURMY_TRASH",
    "WORMADAM_SANDY",
    "WORMADAM_TRASH",
    "SHELLOS_EAST",
    "GASTRODON_EAST",
    "ROTOM_HEAT",
    "ROTOM_WASH",
    "ROTOM_FROST",
    "ROTOM_FAN",
    "ROTOM_MOW",
    "GIRATINA_ORIGIN",
    "SHAYMIN_SKY",
    "ARCEUS_FIGHT",
    "ARCEUS_FLYING",
    "ARCEUS_POISON",
    "ARCEUS_GROUND",
    "ARCEUS_ROCK",
    "ARCEUS_BUG",
    "ARCEUS_GHOST",
    "ARCEUS_STEEL",
    "ARCEUS_FIRE",
    "ARCEUS_WATER",
    "ARCEUS_GRASS",
    "ARCEUS_ELECTRIC",
    "ARCEUS_PSYCHIC",
    "ARCEUS_ICE",
    "ARCEUS_DRAGON",
    "ARCEUS_DARK",
    "BASCULIN_BLUE",
    "DARMANITANZEN",
    "DEERLING_SUMMER",
    "DEERLING_AUTUMN",
    "DEERLING_WINTER",
    "SAWSBUCK_SUMMER",
    "SAWSBUCK_AUTUMN",
    "SAWSBUCK_WINTER",
    "HIPPOPOTAS_F",
    "HIPPOWDON_F",
    "MELOETTA_PIROUETTE",
    "GENESECT_SHOCK",
    "GENESECT_BURN",
    "GENESECT_CHILL",
    "GENESECT_DOUSE",
    "CHERRIM_SUN",
    "KYUREM_BLACK",
    "KYUREM_WHITE",
    "TORNADUS_THERIAN",
    "THUNDURUS_THERIAN",
    "LANDORUS_THERIAN",
    "KELDEO_RESOLUTE",
    "CHESPIN",
    "QUILLADIN",
    "CHESNAUGHT",
    "FENNEKIN",
    "BRAIXEN",
    "DELPHOX",
    "FROAKIE",
    "FROGADIER",
    "GRENINJA",
    "BUNNELBY",
    "DIGGERSBY",
    "FLETCHLING",
    "FLETCHINDER",
    "TALONFLAME",
    "SCATTERBUG",
    "SPEWPA",
    "VIVILLON",
    "LITLEO",
    "PYROAR",
    "FLABEBE",
    "FLOETTE",
    "FLORGES",
    "SKIDDO",
    "GOGOAT",
    "PANCHAM",
    "PANGORO",
    "FURFROU",
    "ESPURR",
    "MEOWSTIC",
    "HONEDGE",
    "DOUBLADE",
    "AEGISLASH",
    "SPRITZEE",
    "AROMATISSE",
    "SWIRLIX",
    "SLURPUFF",
    "INKAY",
    "MALAMAR",
    "BINACLE",
    "BARBARACLE",
    "SKRELP",
    "DRAGALGE",
    "CLAUNCHER",
    "CLAWITZER",
    "HELIOPTILE",
    "HELIOLISK",
    "TYRUNT",
    "TYRANTRUM",
    "AMAURA",
    "AURORUS",
    "SYLVEON",
    "HAWLUCHA",
    "DEDENNE",
    "CARBINK",
    "GOOMY",
    "SLIGGOO",
    "GOODRA",
    "KLEFKI",
    "PHANTUMP",
    "TREVENANT",
    "PUMPKABOO",
    "GOURGEIST",
    "BERGMITE",
    "AVALUGG",
    "NOIBAT",
    "NOIVERN",
    "XERNEAS",
    "YVELTAL",
    "ZYGARDE",
    "DIANCIE",
    "HOOPA",
    "HOOPA_UNBOUND",
    "VOLCANION",
    "PYROAR_FEMALE",
    "MEOWSTIC_FEMALE",
    "AEGISLASH_BLADE",
    "ARCEUS_FAIRY",
    "ZYGARDE_CELL",
    "ZYGARDE_CORE",
    "ZYGARDE_10",
    "ZYGARDE_COMPLETE",
    "ASHGRENINJA",
    "FLABEBE_BLUE",
    "FLABEBE_ORANGE",
    "FLABEBE_YELLOW",
    "FLABEBE_WHITE",
    "FLOETTE_BLUE",
    "FLOETTE_ORANGE",
    "FLOETTE_YELLOW",
    "FLOETTE_WHITE",
    "FLOETTE_ETERNAL",
    "FLORGES_BLUE",
    "FLORGES_ORANGE",
    "FLORGES_YELLOW",
    "FLORGES_WHITE",
    "PUMPKABOO_XL",
    "PUMPKABOO_L",
    "PUMPKABOO_M",
    "GOURGEIST_XL",
    "GOURGEIST_L",
    "GOURGEIST_M",
    "FURFROU_HEART",
    "FURFROU_DIAMOND",
    "FURFROU_STAR",
    "FURFROU_PHAROAH",
    "FURFROU_KABUKI",
    "FURFROU_LA_REINE",
    "FURFROU_MATRON",
    "FURFROU_DANDY",
    "FURFROU_DEBUTANTE",
    "VIVILLON_FANCY",
    "VENUSAUR_MEGA",
    "CHARIZARD_MEGA_X",
    "CHARIZARD_MEGA_Y",
    "BLASTOISE_MEGA",
    "BEEDRILL_MEGA",
    "PIDGEOT_MEGA",
    "ALAKAZAM_MEGA",
    "SLOWBRO_MEGA",
    "GENGAR_MEGA",
    "KANGASKHAN_MEGA",
    "PINSIR_MEGA",
    "GYARADOS_MEGA",
    "AERODACTYL_MEGA",
    "MEWTWO_MEGA_X",
    "MEWTWO_MEGA_Y",
    "AMPHAROS_MEGA",
    "STEELIX_MEGA",
    "SCIZOR_MEGA",
    "HERACROSS_MEGA",
    "HOUNDOOM_MEGA",
    "TYRANITAR_MEGA",
    "SCEPTILE_MEGA",
    "BLAZIKEN_MEGA",
    "SWAMPERT_MEGA",
    "GARDEVOIR_MEGA",
    "SABLEYE_MEGA",
    "MAWILE_MEGA",
    "AGGRON_MEGA",
    "MEDICHAM_MEGA",
    "MANECTRIC_MEGA",
    "SHARPEDO_MEGA",
    "CAMERUPT_MEGA",
    "ALTARIA_MEGA",
    "BANETTE_MEGA",
    "ABSOL_MEGA",
    "GLALIE_MEGA",
    "SALAMENCE_MEGA",
    "METAGROSS_MEGA",
    "LATIAS_MEGA",
    "LATIOS_MEGA",
    "GROUDON_PRIMAL",
    "KYOGRE_PRIMAL",
    "RAYQUAZA_MEGA",
    "LOPUNNY_MEGA",
    "GARCHOMP_MEGA",
    "LUCARIO_MEGA",
    "ABOMASNOW_MEGA",
    "GALLADE_MEGA",
    "AUDINO_MEGA",
    "DIANCIE_MEGA",
    "DIALGA_ORIGIN",
    "PALKIA_ORIGIN",
    "VIVILLON_ARCHIPELAGO",
    "VIVILLON_CONTINENTAL",
    "VIVILLON_ELEGANT",
    "VIVILLON_GARDEN",
    "VIVILLON_HIGH_PLAINS",
    "VIVILLON_ICY_SNOW",
    "VIVILLON_JUNGLE",
    "VIVILLON_MARINE",
    "VIVILLON_MODERN",
    "VIVILLON_MONSOON",
    "VIVILLON_OCEAN",
    "VIVILLON_POKEBALL",
    "VIVILLON_POLAR",
    "VIVILLON_RIVER",
    "VIVILLON_SANDSTORM",
    "VIVILLON_SAVANNA",
    "VIVILLON_SUN",
    "VIVILLON_TUNDRA",
    "ROWLET",
    "DARTRIX",
    "DECIDUEYE",
    "LITTEN",
    "TORRACAT",
    "INCINEROAR",
    "POPPLIO",
    "BRIONNE",
    "PRIMARINA",
    "PIKIPEK",
    "TRUMBEAK",
    "TOUCANNON",
    "YUNGOOS",
    "GUMSHOOS",
    "GRUBBIN",
    "CHARJABUG",
    "VIKAVOLT",
    "CRABRAWLER",
    "CRABOMINABLE",
    "ORICORIO",
    "CUTIEFLY",
    "RIBOMBEE",
    "ROCKRUFF",
    "LYCANROC",
    "WISHIWASHI",
    "MAREANIE",
    "TOXAPEX",
    "MUDBRAY",
    "MUDSDALE",
    "DEWPIDER",
    "ARAQUANID",
    "FOMANTIS",
    "LURANTIS",
    "MORELULL",
    "SHIINOTIC",
    "SALANDIT",
    "SALAZZLE",
    "STUFFUL",
    "BEWEAR",
    "BOUNSWEET",
    "STEENEE",
    "TSAREENA",
    "COMFEY",
    "ORANGURU",
    "PASSIMIAN",
    "WIMPOD",
    "GOLISOPOD",
    "SANDYGAST",
    "PALOSSAND",
    "PYUKUMUKU",
    "TYPE_NULL",
    "SILVALLY",
    "MINIOR_SHIELD",
    "KOMALA",
    "TURTONATOR",
    "TOGEDEMARU",
    "MIMIKYU",
    "BRUXISH",
    "DRAMPA",
    "DHELMISE",
    "JANGMO_O",
    "HAKAMO_O",
    "KOMMO_O",
    "TAPU_KOKO",
    "TAPU_LELE",
    "TAPU_BULU",
    "TAPU_FINI",
    "COSMOG",
    "COSMOEM",
    "SOLGALEO",
    "LUNALA",
    "NIHILEGO",
    "BUZZWOLE",
    "PHEROMOSA",
    "XURKITREE",
    "CELESTEELA",
    "KARTANA",
    "GUZZLORD",
    "NECROZMA",
    "MAGEARNA",
    "MARSHADOW",
    "RATTATA_A",
    "RATICATE_A",
    "RAICHU_A",
    "SANDSHREW_A",
    "SANDSLASH_A",
    "VULPIX_A",
    "NINETALES_A",
    "DIGLETT_A",
    "DUGTRIO_A",
    "MEOWTH_A",
    "PERSIAN_A",
    "GEODUDE_A",
    "GRAVELER_A",
    "GOLEM_A",
    "GRIMER_A",
    "MUK_A",
    "EXEGGCUTE_A",
    "EXEGGUTOR_A",
    "CUBONE_A",
    "MAROWAK_A",
    "DEOXYS_ATTACK",
    "DEOXYS_DEFENSE",
    "DEOXYS_SPEED",
    "ORICORIO_Y",
    "ORICORIO_P",
    "ORICORIO_S",
    "LYCANROC_N",
    "WISHIWASHI_S",
    "SILVALLY_FIGHT",
    "SILVALLY_FLYING",
    "SILVALLY_POISON",
    "SILVALLY_GROUND",
    "SILVALLY_ROCK",
    "SILVALLY_BUG",
    "SILVALLY_GHOST",
    "SILVALLY_STEEL",
    "SILVALLY_FIRE",
    "SILVALLY_WATER",
    "SILVALLY_GRASS",
    "SILVALLY_ELECTRIC",
    "SILVALLY_PSYCHIC",
    "SILVALLY_ICE",
    "SILVALLY_DRAGON",
    "SILVALLY_DARK",
    "SILVALLY_FAIRY",
    "MINIOR_RED",
    "MINIOR_BLUE",
    "MINIOR_ORANGE",
    "MINIOR_YELLOW",
    "MINIOR_INDIGO",
    "MINIOR_GREEN",
    "MINIOR_VIOLET",
    "MIMIKYU_BUSTED",
    "MAGEARNA_P",
    "POIPOLE",
    "NAGANADEL",
    "STAKATAKA",
    "BLACEPHALON",
    "ZERAORA",
    "NECROZMA_DUSK_MANE",
    "NECROZMA_DAWN_WINGS",
    "NECROZMA_ULTRA",
    "LYCANROC_DUSK",
    "MELTAN",
    "MELMETAL",
    "PIKACHU_SURFING",
    "PIKACHU_FLYING",
    "PIKACHU_COSPLAY",
    "PIKACHU_LIBRE",
    "PIKACHU_POP_STAR",
    "PIKACHU_ROCK_STAR",
    "PIKACHU_BELLE",
    "PIKACHU_PHD",
    "PIKACHU_CAP_ORIGINAL",
    "PIKACHU_CAP_HOENN",
    "PIKACHU_CAP_SINNOH",
    "PIKACHU_CAP_UNOVA",
    "PIKACHU_CAP_KALOS",
    "PIKACHU_CAP_ALOLA",
    "PIKACHU_CAP_PARTNER",
    "PICHU_SPIKY",
    "XERNEAS_NATURAL",
    "GROOKEY",
    "THWACKEY",
    "RILLABOOM",
    "SCORBUNNY",
    "RABOOT",
    "CINDERACE",
    "SOBBLE",
    "DRIZZILE",
    "INTELEON",
    "SKWOVET",
    "GREEDENT",
    "ROOKIDEE",
    "CORVISQUIRE",
    "CORVIKNIGHT",
    "BLIPBUG",
    "DOTTLER",
    "ORBEETLE",
    "NICKIT",
    "THIEVUL",
    "GOSSIFLEUR",
    "ELDEGOSS",
    "WOOLOO",
    "DUBWOOL",
    "CHEWTLE",
    "DREDNAW",
    "YAMPER",
    "BOLTUND",
    "ROLYCOLY",
    "CARKOL",
    "COALOSSAL",
    "APPLIN",
    "FLAPPLE",
    "APPLETUN",
    "SILICOBRA",
    "SANDACONDA",
    "CRAMORANT",
    "ARROKUDA",
    "BARRASKEWDA",
    "TOXEL",
    "TOXTRICITY",
    "SIZZLIPEDE",
    "CENTISKORCH",
    "CLOBBOPUS",
    "GRAPPLOCT",
    "SINISTEA",
    "POLTEAGEIST",
    "HATENNA",
    "HATTREM",
    "HATTERENE",
    "IMPIDIMP",
    "MORGREM",
    "GRIMMSNARL",
    "OBSTAGOON",
    "PERRSERKER",
    "CURSOLA",
    "SIRFETCHD",
    "MR_RIME",
    "RUNERIGUS",
    "MILCERY",
    "ALCREMIE_STRAWBERRY",
    "FALINKS",
    "PINCURCHIN",
    "SNOM",
    "FROSMOTH",
    "STONJOURNER",
    "EISCUE",
    "INDEEDEE",
    "MORPEKO",
    "CUFANT",
    "COPPERAJAH",
    "DRACOZOLT",
    "ARCTOZOLT",
    "DRACOVISH",
    "ARCTOVISH",
    "DURALUDON",
    "DREEPY",
    "DRAKLOAK",
    "DRAGAPULT",
    "ZACIAN",
    "ZAMAZENTA",
    "ETERNATUS",
    "KUBFU",
    "URSHIFU_SINGLE",
    "ZARUDE",
    "REGIELEKI",
    "REGIDRAGO",
    "GLASTRIER",
    "SPECTRIER",
    "CALYREX",
    "CRAMORANT_GULPING",
    "CRAMORANT_GORGING",
    "TOXTRICITY_LOW_KEY",
    "SINISTEA_CHIPPED",
    "POLTEAGEIST_CHIPPED",
    "ALCREMIE_BERRY",
    "ALCREMIE_CLOVER",
    "ALCREMIE_FLOWER",
    "ALCREMIE_LOVE",
    "ALCREMIE_RIBBON",
    "ALCREMIE_STAR",
    "EISCUE_NOICE",
    "INDEEDEE_FEMALE",
    "MORPEKO_HANGRY",
    "ZACIAN_CROWNED",
    "ZAMAZENTA_CROWNED",
    "ETERNATUS_ETERNAMAX",
    "URSHIFU_RAPID",
    "ZARUDE_DADA",
    "CALYREX_ICE_RIDER",
    "CALYREX_SHADOW_RIDER",
    "MEOWTH_G",
    "PONYTA_G",
    "RAPIDASH_G",
    "SLOWPOKE_G",
    "SLOWBRO_G",
    "FARFETCHD_G",
    "KOFFING_G",
    "WEEZING_G",
    "MIME_JR_G",
    "MR_MIME_G",
    "ARTICUNO_G",
    "ZAPDOS_G",
    "MOLTRES_G",
    "SLOWKING_G",
    "CORSOLA_G",
    "ZIGZAGOON_G",
    "LINOONE_G",
    "DARUMAKA_G",
    "DARMANITAN_G",
    "DARMANITAN_G_ZEN",
    "YAMASK_G",
    "STUNFISK_G",
    "GROWLITHE_H",
    "ARCANINE_H",
    "VOLTORB_H",
    "ELECTRODE_H",
    "TYPHLOSION_H",
    "QWILFISH_H",
    "SNEASEL_H",
    "SAMUROTT_H",
    "LILLIGANT_H",
    "BASCULIN_H",
    "ZORUA_H",
    "ZOROARK_H",
    "BRAVIARY_H",
    "SLIGGOO_H",
    "GOODRA_H",
    "AVALUGG_H",
    "DECIDUEYE_H",
    "WYRDEER",
    "KLEAVOR",
    "URSALUNA",
    "BASCULEGION_M",
    "BASCULEGION_F",
    "SNEASLER",
    "OVERQWIL",
    "ENAMORUS",
    "ENAMORUS_THERIAN",
    "VENUSAUR_GIGA",
    "CHARIZARD_GIGA",
    "BLASTOISE_GIGA",
    "BUTTERFREE_GIGA",
    "PIKACHU_GIGA",
    "MEOWTH_GIGA",
    "MACHAMP_GIGA",
    "GENGAR_GIGA",
    "KINGLER_GIGA",
    "LAPRAS_GIGA",
    "EEVEE_GIGA",
    "SNORLAX_GIGA",
    "GARBODOR_GIGA",
    "MELMETAL_GIGA",
    "RILLABOOM_GIGA",
    "CINDERACE_GIGA",
    "INTELEON_GIGA",
    "CORVIKNIGHT_GIGA",
    "ORBEETLE_GIGA",
    "DREDNAW_GIGA",
    "COALOSSAL_GIGA",
    "FLAPPLE_GIGA",
    "APPLETUN_GIGA",
    "SANDACONDA_GIGA",
    "TOXTRICITY_GIGA",
    "TOXTRICITY_LOW_KEY_GIGA",
    "CENTISKORCH_GIGA",
    "HATTERENE_GIGA",
    "GRIMMSNARL_GIGA",
    "ALCREMIE_GIGA",
    "COPPERAJAH_GIGA",
    "DURALUDON_GIGA",
    "URSHIFU_SINGLE_GIGA",
    "URSHIFU_RAPID_GIGA",
]

pokemon_name_mappings = dict()
move_pokemon_mapping = dict()

def normalize_name_wrapper(name):
    def normalize_name(name):
        regex_gigantamax = r"(.*)_GIGA$"
        subst_gigantamax = r"\g<1> Gigantamax"
        sub_gigantamax = lambda str: re.sub(regex_gigantamax, subst_gigantamax, str, 0)

        regex_hisuian = r"^(?!UNOWN)(.*)_H$"
        subst_hisuian = r"Hisuian \g<1>"
        sub_hisuian = lambda str: re.sub(regex_hisuian, subst_hisuian, str, 0)

        regex_galarian = r"^(?!UNOWN)(.*)_G$"
        subst_galarian = r"Galarian \g<1>"
        sub_galarian = lambda str: re.sub(regex_galarian, subst_galarian, str, 0)

        regex_galarian_zen = r"(.*)_G_ZEN$"
        subst_galarian_zen = r"Galarian \g<1> Zen"
        sub_galarian_zen = lambda str: re.sub(
            regex_galarian_zen, subst_galarian_zen, str, 0
        )

        regex_alolan = r"^(?!UNOWN)(.*)_A$"
        subst_alolan = r"Alolan \g<1>"
        sub_alolan = lambda str: re.sub(regex_alolan, subst_alolan, str, 0)

        regex_male = r"^(?!UNOWN)(.*)_M$"
        subst_male = r"\g<1> Male"
        sub_male = lambda str: re.sub(regex_male, subst_male, str, 0)

        regex_female = r"^(?!UNOWN)(.*)_(F|FEMALE)$"
        subst_female = r"\g<1> Female"
        sub_female = lambda str: re.sub(regex_female, subst_female, str, 0)

        regex_rapid = r"(.*)_RAPID$"
        subst_rapid = r"\g<1> Rapid Strike"
        sub_rapid = lambda str: re.sub(regex_rapid, subst_rapid, str, 0)

        regex_single = r"(.*)_SINGLE$"
        subst_single = r"\g<1> Single Strike"
        sub_single = lambda str: re.sub(regex_single, subst_single, str, 0)

        regex_school = r"(WISHIWASHI)_S$"
        subst_school = r"\g<1> School"
        sub_school = lambda str: re.sub(regex_school, subst_school, str, 0)

        regex_oricorio_y = r"^(ORICORIO)_Y$"
        subst_oricorio_y = r"\g<1> Pom-Pom"
        sub_oricorio_y = lambda str: re.sub(regex_oricorio_y, subst_oricorio_y, str, 0)

        regex_oricorio_p = r"^(ORICORIO)_P$"
        subst_oricorio_p = r"\g<1> Pa'u"
        sub_oricorio_p = lambda str: re.sub(regex_oricorio_p, subst_oricorio_p, str, 0)

        regex_oricorio_s = r"^(ORICORIO)_S$"
        subst_oricorio_s = r"\g<1> Sensu"
        sub_oricorio_s = lambda str: re.sub(regex_oricorio_s, subst_oricorio_s, str, 0)

        regex_oricorio = r"^(ORICORIO)$"
        subst_oricorio = r"\g<1> Baile"
        sub_oricorio = lambda str: re.sub(regex_oricorio, subst_oricorio, str, 0)

        # kommo-o line
        regex_kommoo = r"(.*)O_O$"
        subst_kommoo = r"\g<1>O-O"
        sub_kommoo = lambda str: re.sub(regex_kommoo, subst_kommoo, str, 0)

        # Mega evolutions
        regex_mega = r"(.*)_MEGA$"
        subst_mega = r"Mega \g<1>"
        sub_mega = lambda str: re.sub(regex_mega, subst_mega, str, 0)
        regex_mega_x = r"(.*)_MEGA_X$"
        subst_mega_x = r"Mega \g<1> X"
        sub_mega_x = lambda str: re.sub(regex_mega_x, subst_mega_x, str, 0)
        regex_mega_y = r"(.*)_MEGA_Y$"
        subst_mega_y = r"Mega \g<1> Y"
        sub_mega_y = lambda str: re.sub(regex_mega_y, subst_mega_y, str, 0)

        # Red (Basculin)
        regex_red = r"(.*)_RED$"
        subst_red = r"\g<1> Red"
        sub_red = lambda str: re.sub(regex_red, subst_red, str, 0)

        # Blue (Basculin)
        regex_blue = r"(.*)_BLUE$"
        subst_blue = r"\g<1> Blue"
        sub_blue = lambda str: re.sub(regex_blue, subst_blue, str, 0)

        # Z (Porygon)
        regex_Z = r"^(?!UNOWN)(.*)_Z$"
        subst_Z = r"\g<1>-Z"
        sub_Z = lambda str: re.sub(regex_Z, subst_Z, str, 0)

        # Z (Porygon)
        regex_2 = r"^(?!UNOWN)2$"
        subst_2 = r"\g<1>-2"
        sub_2 = lambda str: re.sub(regex_2, subst_2, str, 0)

        # NULL (Type : NULL)
        regex_null = r"(.*)_NULL$"
        subst_null = r"\g<1>:NULL"
        sub_null = lambda str: re.sub(regex_null, subst_null, str, 0)

        if re.search(regex_gigantamax, name) is not None:
            return sub_gigantamax(name)
        elif re.search(regex_hisuian, name) is not None:
            return sub_hisuian(name)
        elif re.search(regex_galarian, name) is not None:
            return sub_galarian(name)
        elif re.search(regex_galarian_zen, name) is not None:
            return sub_galarian_zen(name)
        elif re.search(regex_alolan, name) is not None:
            return sub_alolan(name)
        elif re.search(regex_male, name) is not None:
            return sub_male(name)
        elif re.search(regex_female, name) is not None:
            return sub_female(name)
        elif re.search(regex_single, name) is not None:
            return sub_single(name)
        elif re.search(regex_rapid, name) is not None:
            return sub_rapid(name)
        elif re.search(regex_school, name) is not None:
            return sub_school(name)

        # oricorio
        elif re.search(regex_oricorio_s, name) is not None:
            return sub_oricorio_s(name)
        elif re.search(regex_oricorio_p, name) is not None:
            return sub_oricorio_p(name)
        elif re.search(regex_oricorio_y, name) is not None:
            return sub_oricorio_y(name)
        elif re.search(regex_oricorio, name) is not None:
            return sub_oricorio(name)

        # kommoo
        elif re.search(regex_kommoo, name) is not None:
            return sub_kommoo(name)

        # mega
        elif re.search(regex_mega, name) is not None:
            return sub_mega(name)
        elif re.search(regex_mega_x, name) is not None:
            return sub_mega_x(name)
        elif re.search(regex_mega_y, name) is not None:
            return sub_mega_y(name)
        # basculin
        elif re.search(regex_red, name) is not None:
            return sub_red(name)
        elif re.search(regex_blue, name) is not None:
            return sub_blue(name)
        # porygon Z
        elif re.search(regex_Z, name) is not None:
            return sub_Z(name)
        # porygon 2
        elif re.search(regex_2, name) is not None:
            return sub_2(name)
        # type : null
        elif re.search(regex_null, name) is not None:
            return sub_null(name)

        return name

    return normalize_name(name).replace("_", " ").title()


for name in pokemon_names:
    fixed_name = normalize_name_wrapper(name)
    pokemon_name_mappings[name] = fixed_name


paths = [filepath.replace("./data\\", "./data/") for filepath in glob.iglob("./data/*.txt")]



for path in paths:
    # open the file for that path
    with open(path) as file:
        lines = [l.strip("\n") for l in file.readlines()]
        move_info = lines[0]
        pokemon_list = lines[1:]
        fixed_pokemon_names = [pokemon_name_mappings.get(n, n) for n in pokemon_list]
        
        move_pokemon_mapping[move_info] = fixed_pokemon_names
    # break

# print(move_pokemon_mapping)

output_path = "./tutor_mappings.json"
with open(output_path, "w") as outfile:
    json.dump(move_pokemon_mapping, outfile, indent=2)

print("done")